### ISSUE TITLE
[BUG] Token is not hidden again when clicked outside of the token input box

### ISSUE THREAD

**Issue by OlexG** [cookiedb/cloud-feedback#5]
**Describe the bug**
Initially, the token for a database is hidden (in the settings tab). It is revealed when you click on the input box. I believe it is expected behavior to hide it again when anywhere outside of the input box is clicked.

**To Reproduce**
1. Go to db settings
2. Click on the token
3. Click outside of the input box

**Expected behavior**
The token to hide again

**Comment by lino-levan** [comment]
Not technically a bug, but this is expected behavior from the user side. Thanks for reporting!

**Comment by lino-levan** [comment]
This is fixed in the latest release. Thanks for reporting!
