### ISSUE TITLE
[BUG] 404 not found when trying to see demo

### ISSUE THREAD

**Issue by OlexG** [cookiedb/cloud-feedback#6]
**Describe the bug**
The demo page seems to return 404

**To Reproduce**
1. Go to home page
2. Click on demo 

**Expected behavior**
Demo page shown 

**Desktop (please complete the following information):**
 - OS: iOS 
 - Browser chrome

**Comment by lino-levan** [comment]
I've removed the demo for now. Closing this issue and may re-open when we consider re-implementing
